---
title: "第1回研究会"
subtitle: "The 1st Workshop"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**第1回北海道言語科学会研究会**は、**2026年2月28日（土）**に**小樽商科大学**で行われます。

**The 1st Workshop of the Hokkaido Language Science Society** will take place at **Otaru University of Commerce** at **28 February 2026 (Sat)**.
  
 * 参加資格：どなたでもご参加いただけます（道外，海外の方も歓迎）
    * Partipants: Anyone can participate, Hokkaido resident or not, regardless of nationality.
 * 招待講演：[トーマス・ヴァヌイ](https://www.thomasvanhoey.com/) (ルーヴェン・カトリック大学) 
   * Invited speaker: [Thomas Van Hoey](https://www.thomasvanhoey.com/) (UCLouvain) 
     * **Accommodating path and manner in the lexical aspect of iconic words**
 * 要旨規定：1000文字以内の日本語、または500単語以内の英語。書式自由。言語学関連のテーマは全て可能。
   * Abstract: Max. 500 words in English or 1,000 characters in Japanese. Free format. Any subfield of linguistics welcome.
 * 投稿締切：2026年1月31日までに[朱易安のメール](mailto:joo@res.otaru-uc.ac.jp)へ送ってください
   * Submission deadline: Please send your abstract to [Ian Joo's email address](mailto:joo@res.otaru-uc.ac.jp) by 31 January 2026
 * 結果通知：投稿後、 一週間以内に通知
   * Results notification: Within a week after the submission
 * 登録料金：1000円
   * Registration fee: 1,000 yen
